SUBROUTINE BLKDWN
   !!
   !!  GO TO THE NEXT LOWER BLOCK SET.
   !!

   USE RM_Blocks, only: BLKCLR
   USE RM_BufferData, only: BUFFER
   USE Files, only : CURBLK, MODFLG
   USE Utils, only : ZEROIT

   implicit none

   INCLUDE 'incore.inc'

   INTEGER :: II, IB, IN

   CALL BLKCLN
   DO II=10,20
      CALL BLKCLR(II)
   END DO

   IF (NEXT .LT. 69+1) GOTO 900
   !
   !  GET THE OLD BLOCK SET INFO.
   IB = NEXT - 69
   IN = NEXT - 7
   CALL BLKMOV(BLOCKS,BUFFER(IB),63)
   CALL BLKMOV(CURBLK,BUFFER(IB+63),3)
   CALL BLKMOV(MODFLG,BUFFER(IB+66),3)
   NUMBL = BUFFER(IN)
   CALL ZEROIT(BUFFER(IB),69)
   NEXT = IB
900 CONTINUE
   RETURN
END SUBROUTINE BLKDWN
