      FUNCTION CHRASC(ASCHR)
      INCLUDE 'syspar.inc'
C
C     **UNIX SYSTEM DEPENDENT INTERNAL ROUTINE **
C
C     RETURN THE CHARACTER EQUIVALENT OF ASCHR (ASCII-CHAR)
C
      CHARACTER*1 CHRASC
      INTEGER ASCHR
C
      CHRASC = CHAR(ASCHR)
      RETURN
      END
