MODULE Lexer
   implicit none
   private

   INTEGER, PARAMETER, public :: ASPACE=32
   INTEGER, PARAMETER, public :: LA=97,LZ=122,UA=65,UZ=90,USCOR=95
   INTEGER, PARAMETER, public :: UECH=69,LECH=101
   INTEGER, PARAMETER, public :: U0=48,U9=57,PLSIGN=43,MNSIGN=45,DECIM=46
   INTEGER, PARAMETER, public :: TMSIGN=42,DVSIGN=47
   INTEGER, PARAMETER, public :: ATSIGN=64,PCSIGN=37
   INTEGER, PARAMETER, public :: EQSIGN=61,GTSIGN=62,LTSIGN=60,SQUOTE=39
   INTEGER, PARAMETER, public :: DQUOTE=34
   INTEGER, PARAMETER, public :: ASSTAR=42,ASPCNT=37
   INTEGER, PARAMETER, public :: ASCOLN=58
   INTEGER, PARAMETER, public :: ASRCLL=82,ASLXEI=60,ASLXEE=62
   INTEGER, PARAMETER, public :: ASLXEX=33,ASLXES=35

   INTEGER, public :: ASBLK,ASCOM,ASSEMI,ASPLUS,ASQUO
   INTEGER, public  :: ASLPAR, ASRPAR

!  VARIABLE DEFINITIONS
!         ASBLK---FIELD SEPERATOR (MANY = 1)
!         ASCOM---FIELD SEPERATOR (MANY = MANY)
!         ASSEMI--RECORD DELIMITER
!-----C   ASDOL---RECORD DELIMITER (ARCHAIC)
!         ASPLUS--LINE CONTINUATION CHARACTER
!         ASQUO---STRING DELIMITER  (' OR ")
!         ASLPAR--LEFT PARENTHESIS
!         ASRPAR--RIGHT PARENTHESIS
!         ASPCNT--PERCENT SIGN
!
!         ASRCLL--RECALL LINE CHARACTER (R)
!         ASRCLC--RECALL COMMAND CHARACTER (RC)
!         ASLXEI--RECALL EDIT - BEGIN INSERT (>)
!         ASLXEE--RECALL EDIT - END INSERT (<)
!         ASLXEX--RECALL EDIT - END LINE (!)
!         ASLXES--RECALL EDIT - SKIP CHAR (#)

   public Initialise

contains

   SUBROUTINE Initialise
      !
      !     INITIALIZE THE LXLCOM VARIABLES
      !
      INTRINSIC ICHAR

      ASBLK  = ICHAR(' ')
      ASCOM  = ICHAR(',')
      ASPLUS = ICHAR('+')
      ASQUO  = SQUOTE
      ASLPAR = ICHAR('(')
      ASRPAR = ICHAR(')')
      ASSEMI = ICHAR(';')
      RETURN
   END


END MODULE Lexer
