MODULE RM_Parameters
   !! Constants used throughout RIM

   USE iso_fortran_env, only : character_storage_size, numeric_storage_size, output_unit, input_unit

   implicit none
   private

   ! ------------- WORD AND NAME LENGTH -------------
   !
   !        ZCW       = NUMBER OF CHARACTERS IN A WORD
   !        ZC        = NUMBER OF CHARACTERS IN A NAME
   !        Z         = NUMBER OF INTEGERS PER NAME
   !
   INTEGER, PARAMETER, public :: ZC = 16
   INTEGER, PARAMETER, public :: ZCW = numeric_storage_size / character_storage_size
   INTEGER, PARAMETER, public :: Z = ZC / ZCW
   !
   !        ZKEYWL       = MAX CHARACTERS IN A KEYWORD
   !
   INTEGER, PARAMETER, public :: ZKEYWL=12
   !
   !
   !     ------------- PHYSICAL RECORD LENGTH -------------
   !
   !        ZF1       = LENGTH OF FILE 1 PAGE
   !        ZF2       = LENGTH OF FILE 2 PAGE
   !        ZF3       = LENGTH OF FILE 3 PAGE
   !
   INTEGER, PARAMETER, public :: ZF1=1024
   INTEGER, PARAMETER, public :: ZF2=1024
   INTEGER, PARAMETER, public :: ZF3=126
   !
   !
   !     ------------- FILE HEADERS -------------
   !
   !        ZF1HDR    = LENGTH OF DATABASE FILE 1 HEADER
   !        ZF2HDR    = LENGTH OF DATABASE FILE 2 HEADER
   !        ZF3HDR    = LENGTH OF DATABASE FILE 3 HEADER
   !        ZFXH..    = POINTERS TO ITEMS IN ALL HEADERS
   !        ZF1H..    = POINTERS TO ITEMS IN FILE 1
   !        ZF2H..    = POINTERS TO ITEMS IN FILE 2
   !        ZF3H..    = POINTERS TO ITEMS IN FILE 3
   !
   !        ZFXHID    = GRIM DATABASE IDENTIFICATION
   !        ZFXHVS    = GRIM VERSION NUMBER
   !        ZFXHDB    = DATABASE NAME
   !        ZFXHOW    = OWNER NAME
   !        ZFXHDT    = LAST UPDATE DATE
   !        ZFXHTM    = LAST UPDATE TIME
   !
   INTEGER, PARAMETER, public :: ZFXHID=1
   INTEGER, PARAMETER, public :: ZFXHVS=ZFXHID+Z
   INTEGER, PARAMETER, public :: ZFXHDB=ZFXHVS+1
   INTEGER, PARAMETER, public :: ZFXHOW=ZFXHDB+Z
   INTEGER, PARAMETER, public :: ZFXHDT=ZFXHOW+Z
   INTEGER, PARAMETER, public :: ZFXHTM=ZFXHDT+1
   !
   !        ZF1HLR    = LAST USED FILE 1 RECORD
   !        ZF1HNR    = NEXT AVAILABLE RELATION ROW
   !        ZF1HNA    = NEXT AVAILABLE ATTRIBUTE ROW
   !        ZF1HNL    = NEXT AVAILABLE LINK ROW
   !
   INTEGER, PARAMETER, public :: ZF1HLR=ZFXHTM+1
   INTEGER, PARAMETER, public :: ZF1HNR=ZF1HLR+1
   INTEGER, PARAMETER, public :: ZF1HNA=ZF1HNR+1
   INTEGER, PARAMETER, public :: ZF1HNL=ZF1HNA+1
   INTEGER, PARAMETER, public :: ZF1HDR=ZF1HNL
   !
   !        ZF2HLR    = CURRENT FILE 2 RECORD FOR ADDING DATA
   !        ZF1HNW    = NEXT AVAILABLE WORD FOR ADDING DATA
   !
   INTEGER, PARAMETER, public :: ZF2HLR=ZFXHTM+1
   INTEGER, PARAMETER, public :: ZF2HNW=ZF2HLR+1
   INTEGER, PARAMETER, public :: ZF2HDR=ZF2HNW
   !
   !        ZF3HLR    = NEXT AVAILABLE RECORD FOR B-TREES
   !        ZF3HMO    = CURRENT MOT RECORD
   !        ZF3HNM    = NEXT AVAILABLE WORD IN CURRENT MOT RECORD
   !        ZF3HRC    = START OF THE B-TREE FREE-RECORD CHAIN
   !        ZF3HMC    = START OF THE B-TREE FREE-MOT CHAIN
   !
   INTEGER, PARAMETER, public :: ZF3HLR=ZFXHTM+1
   INTEGER, PARAMETER, public :: ZF3HMO=ZF3HLR+1
   INTEGER, PARAMETER, public :: ZF3HNM=ZF3HMO+1
   INTEGER, PARAMETER, public :: ZF3HRC=ZF3HNM+1
   INTEGER, PARAMETER, public :: ZF3HMC=ZF3HRC+1
   INTEGER, PARAMETER, public :: ZF3HDR=ZF3HMC
   !
   !
   !     ------------- RELATION, ATTRIBUTE, AND LINK TABLES -----------
   !
   !        ZRELL     = LENGTH OF RELATION ROW IN FILE 1
   !        ZRELR     = NUMBER OF RELATION ROWS PER PAGE
   !        ZRELRI    = INITIAL RELATION ROW
   !        ZR1-ZR10  = POINTERS TO ITEMS IN RELATION ROW
   !
   INTEGER, PARAMETER, public :: ZRELL=7+3*Z
   INTEGER, PARAMETER, public :: ZRELR=ZF1/ZRELL
   INTEGER, PARAMETER, public :: ZRELRI=ZRELR+1
   INTEGER, PARAMETER, public :: ZR1=1
   INTEGER, PARAMETER, public :: ZR2=ZR1+1
   INTEGER, PARAMETER, public :: ZR3=ZR2+Z
   INTEGER, PARAMETER, public :: ZR4=ZR3+1
   INTEGER, PARAMETER, public :: ZR5=ZR4+1
   INTEGER, PARAMETER, public :: ZR6=ZR5+1
   INTEGER, PARAMETER, public :: ZR7=ZR6+1
   INTEGER, PARAMETER, public :: ZR8=ZR7+1
   INTEGER, PARAMETER, public :: ZR9=ZR8+1
   INTEGER, PARAMETER, public :: ZR10=ZR9+Z
   !
   !
   !        ZATTL     = LENGTH OF ATTRIBUTE ROW IN FILE 1
   !        ZATTR     = NUMBER OF ATTRIBUTE ROWS PER PAGE
   !        ZATTRI    = INITIAL ATTRIBUTE ROW
   !        ZA1-ZA7   = POINTERS TO ITEMS IN ATTRIBUTE ROW
   !
   INTEGER, PARAMETER, public :: ZATTL=6+2*Z
   INTEGER, PARAMETER, public :: ZATTR=ZF1/ZATTL
   INTEGER, PARAMETER, public :: ZATTRI=(ZATTR*2)+1
   INTEGER, PARAMETER, public :: ZA1=1
   INTEGER, PARAMETER, public :: ZA2=ZA1+1
   INTEGER, PARAMETER, public :: ZA3=ZA2+Z
   INTEGER, PARAMETER, public :: ZA4=ZA3+Z
   INTEGER, PARAMETER, public :: ZA5=ZA4+1
   INTEGER, PARAMETER, public :: ZA6=ZA5+1
   INTEGER, PARAMETER, public :: ZA7=ZA6+1
   INTEGER, PARAMETER, public :: ZA8=ZA7+1
   !
   !
   !        ZLNKL     = LENGTH OF LINK ROW IN FILE 1
   !        ZLNKR     = NUMBER OF LINK ROWS PER PAGE
   !        ZLNKRI    = INITIAL LINK ROW
   !        ZL1-ZL5   = POINTERS TO ITEMS IN LINK ROW
   !
   INTEGER, PARAMETER, public :: ZLNKL=1+5*Z
   INTEGER, PARAMETER, public :: ZLNKR=ZF1/ZLNKL
   INTEGER, PARAMETER, public :: ZLNKRI=(ZLNKR*3)+1
   INTEGER, PARAMETER, public :: ZL1=1
   INTEGER, PARAMETER, public :: ZL2=ZL1+1
   INTEGER, PARAMETER, public :: ZL3=ZL2+Z
   INTEGER, PARAMETER, public :: ZL4=ZL3+Z
   INTEGER, PARAMETER, public :: ZL5=ZL4+Z
   INTEGER, PARAMETER, public :: ZL6=ZL5+Z
   !
   !
   !     ------------- RIM COMMAND LIMITS -----------
   !
   !        ZMTOK     = MAX NUMBER OF INPUT TOKENS
   !        ZMASC     = MAX LENGTH OF INPUT ASCII-TEXT
   !        ZMSRT     = MAX SORT ATTRIBUTES
   !        ZMSEL     = MAX SELECT ATTRIBUTES
   !        ZMSLK     = MAX SELECT LINKS
   !        ZMWHR     = MAX NUMBER OF WHERE CLAUSE ATTRIBUTES
   !        ZMWHLL    = MAX NUMBER OF WHERE CLAUSE VALUE ITEMS
   !        ZMWHVL    = MAX LENGTH OF WHERE CLAUSE VALUE ASCII-TEXT
   !        ZMXMAC    = MAX NUMBER OF MACRO DEFINITIONS
   !        ZMXMTX    = MAX WORDS OF MACRO DEFINITION TEXT
   !        ZMEOP     = MAX OPERATORS IN EXPRESSIONS (REPORT WRITER)
   !
   INTEGER, PARAMETER, public :: ZMTOK=300
   INTEGER, PARAMETER, public :: MAXCOL = ZMTOK
   INTEGER, PARAMETER, public :: ZMASC=ZMTOK*ZCW
   INTEGER, PARAMETER, public :: ZMSRT=10
   INTEGER, PARAMETER, public :: ZMSEL=35
   INTEGER, PARAMETER, public :: ZMSLK=5
   INTEGER, PARAMETER, public :: ZMWHR=15
   INTEGER, PARAMETER, public :: ZMWHVL=300,ZMWHLL=100
   INTEGER, PARAMETER, public :: ZMXMAC=50, ZMXMTX=500
   INTEGER, PARAMETER, public :: ZMEOP=20
   !
   !
   !     ------------- BUFFER SIZES -----------
   !
   !        ZIOIN     = NUMBER SIMULTANEOUS INPUT FILES
   !        ZIOOU     = NUMBER SIMULTANEOUS OUTPUT FILES
   !        ZIOBF     = SIZE OF FILE BUFFERS
   !        ZPIMAX    = MAX PROGRAMMABLE INTERFACE POINTER
   !
   INTEGER, PARAMETER, public :: ZIOIN=1
   INTEGER, PARAMETER, public :: ZIOOU=2
   INTEGER, PARAMETER, public :: ZIOBF=1
   INTEGER, PARAMETER, public :: ZPIMAX=9
   !
   !        ZICBL     = NUMBER OF IN-CORE BLOCKS
   !        ZBT       = BTBUF'S CORE ARRAY SIZE (ZICBL*ZF3)
   !        ZBUF      = LENGTH OF /RIMCOM/ BUFFER AREA
   !
   INTEGER, PARAMETER, public :: ZBF4=484
   INTEGER, PARAMETER, public :: ZICBL=20
   INTEGER, PARAMETER, public :: ZBT=ZICBL*ZF3
   INTEGER, PARAMETER, public :: ZBUF=20000
   !
   !
   !     ------------- TEXT IO LIMITS -----------
   !
   !        ZCARDL       = MAX LENGTH OF CARD INPUT RECORDS
   !        ZCARDW       = MAX LENGTH OF CARD INPUT RECORDS (WORDS) - input width
   !        ZCARDN       = NUMBER OF INPUT RECORDS FOR RECALL (FOR EDIT)
   !        ZPRINL       = MAX LENGTH OF PRINTER OUTPUT RECORDS
   !        ZPRINW       = MAX LENGTH OF PRINTER OUTPUT RECORDS (WORDS)
   !
   INTEGER, PARAMETER, public :: ZCARDL=512
   INTEGER, PARAMETER, public :: ZCARDW=(ZCARDL-1)/ZCW+1
   INTEGER, PARAMETER, public :: ZCARDN=10
   INTEGER, PARAMETER, public :: ZPRINL=512
   INTEGER, PARAMETER, public :: ZPRINW=(ZPRINL-1)/ZCW+1
   !
   !        ZDATL        = LENGTH OF RIM DATE FIELDS
   !        ZTIML        = LENGTH OF RIM TIME FIELDS
   !
   INTEGER, PARAMETER, public :: ZDATL=8,ZTIML=8
   !
   !
   !     ------------- I/O NAMES AND UNITS ----------
   !
   !        ZFNAML       = MAX FILENAME LENGTH
   !        ZTRMIN       = TERMINAL INPUT FILENAME
   !        ZTRMOU       = TERMINAL OUTPUT FILENAME
   !        ZHFNAM       = HELP DB FILENAME
   !
   INTEGER, PARAMETER, public :: ZFNAML=100
   CHARACTER(6), PARAMETER, public :: ZTRMIN='stdin ', ZTRMOU='stdout'
   CHARACTER(8), PARAMETER, public :: ZHFNAM = 'rim_help'
   !
   !
   !        ZNINT        = UNIT FOR TERMINAL INPUT
   !        ZNINTA       = UNIT FOR ALTERNATE TERMINAL INPUT
   !        ZNOUT        = UNIT FOR TERMINAL OUTPUT
   !        ZNOUTR       = UNIT FOR REPORT OUTPUT
   !        ZNOUTL       = UNIT FOR LOG OUTPUT
   !        ZNOUTT       = UNIT FOR TRACE OUTPUT
   !
   !        ZNFIL1       = UNIT FOR DATABASE FILE 1
   !        ZNFIL2       = UNIT FOR DATABASE FILE 2
   !        ZNFIL3       = UNIT FOR DATABASE FILE 3
   !
   !        ZNSRT        = UNITS FOR SORTING
   !                       (ALLOCATES ZNSRT THROUGH ZNSRT+ZPIMAX)
   !        ZNSRT1       = SORT SCRATCH UNIT
   !        ZCSRT1       = SORT SCRATCH NAME
   !        ZNSRT2       = SORT SCRATCH UNIT
   !        ZCSRT2       = SORT SCRATCH NAME
   !        ZFSORT       = LENGTH OF SORT FILE BLOCKS
   !
   INTEGER, PARAMETER, public :: ZNINT=input_unit
   INTEGER, PARAMETER, public :: ZNINTA=4
   INTEGER, PARAMETER, public :: ZNOUT= output_unit
   INTEGER, PARAMETER, public ::  ZNOUTR=7, ZNOUTL=8, ZNOUTT=9
   INTEGER, PARAMETER, public :: ZNFIL1=31, ZNFIL2=ZNFIL1+1, ZNFIL3=ZNFIL1+2
   INTEGER, PARAMETER, public :: ZNSRT=40
   INTEGER, PARAMETER, public :: ZNSRT1=38, ZNSRT2=39
   CHARACTER(ZFNAML), PARAMETER, public :: ZCSRT1='RIM.SCRATCH1'
   CHARACTER(ZFNAML), PARAMETER, public :: ZCSRT2='RIM.SCRATCH2'
   INTEGER, PARAMETER, public :: ZFSORT=1024
   !
   !
   !     ------------- SPECIAL NUMBERS ------------
   !
   !        NULL VALUES ('MISSING' AND 'NOT APPLICABLE')
   !
   !        ZIMISS       = MISSING VALUE FOR INTEGERS
   !        ZRMISS       = MISSING VALUE FOR REALS (NOTE TYPE INTEGER)
   !        ZTMISS       = MISSING VALUE FOR TEXT
   !
   !        ZINAPP       = NOT APPLICABLE FOR INTEGERS
   !        ZRNAPP       = NOT APPLICABLE FOR REALS (NOTE TYPE INTEGER)
   !        ZTNAPP       = NOT APPLICABLE FOR TEXT
   !
   !        ZTEND        = FLAG FOR END OF KEY CHAINS
   !                       (GREATER THAN INFINITY)
   !        ENDWRD       = ZTEND
   !        ALL9S        = INFINITY
   !                       (THIS IS MAXIMUM ALLOWABLE INTEGER + 1)
   !
   !        MIN9S        = MINUS INFINITY
   !                       (THIS IS MINIMUM ALLOWABLE INTEGER - 1)
   !
   !        NULL         = AN ALTERNATE MISSING VALUE
   !
   !        BY COINCIDENCE (?) THE NULLS ARE ALL THE SAME ON MOST MACHINES
   !        AS ARE THE NOT APPLICABLES
   !        NOTE.. 2 AVAILABLE INTEGERS FOR FLAGS
   !
   INTEGER, PARAMETER, public :: ZIMISS=2147483647
   INTEGER, PARAMETER, public :: ZRMISS=ZIMISS, ZTMISS=ZIMISS
   INTEGER, PARAMETER, public :: NULL=ZIMISS
   INTEGER, PARAMETER, public :: ZINAPP=ZIMISS-1
   INTEGER, PARAMETER, public :: ZRNAPP=ZINAPP, ZTNAPP=ZINAPP
   INTEGER, PARAMETER, public :: ZTEND=ZIMISS-4
   INTEGER, PARAMETER, public :: ENDWRD=ZTEND
   INTEGER, PARAMETER, public :: ALL9S=ZIMISS-5
   INTEGER, PARAMETER, public :: MIN9S=0-ALL9S
   !
   !        ZHALF        = HALFWORD
   !        ZHTOI        = PACKING FACTOR USED BY ITOH/HTOI
   !                       (NOTE.. REMAINDER OF THE WORD MUST BE
   !                        LARGER THAN LARGEST FILE BLOCK SIZE)
   !
   INTEGER, PARAMETER, public :: ZHALF=2**16
   INTEGER, PARAMETER, public :: ZHTOI=2**20

END MODULE
