      SUBROUTINE AMSG(MTEXT,NUMC,MCONT)
C
C     DUMMY ROUTINE FOR USER LIBRARY
C
         CHARACTER*(*) MCONT
         RETURN
      END


      SUBROUTINE DMSG(JDAT,DFMT,MCONT)
C
C     DUMMY ROUTINE FOR USER LIBRARY
C
         CHARACTER*(*) MCONT
         RETURN
      END


      SUBROUTINE IMSG(NUM,NUMC,MCONT)
C
C     DUMMY ROUTINE FOR USER LIBRARY
C
         CHARACTER*(*) MCONT
         RETURN
      END


      SUBROUTINE MSG(MTYPE,MTEXT,MCONT)
         USE Globals, only : RMSTAT
C
C     DUMMY ROUTINE FOR USER LIBRARY
C
C     IF THIS IS ERROR MESSAGE AND RMSTAT <> 0 THEN SET RMSTAT
C
         CHARACTER*(*) MTYPE, MTEXT, MCONT
C
         IF (MTYPE(1:1).EQ.'E' .AND. RMSTAT.EQ.0) RMSTAT = 999
         RETURN
      END


      SUBROUTINE MSGCMV(MTEXT,CTYPE)
C
C     DUMMY ROUTINE FOR USER LIBRARY
C
         CHARACTER*(*) CTYPE, MTEXT
         RETURN
      END
