SUBROUTINE SELPUT(VAL,TYP,FMT,START,STRING)
   !! THIS ROUTINE PUTS AN ACTUAL VALUE (NON-RM_Text) INTO STRING.
   !! VAL ---- VALUE
   !! TYP ---- FROM TYPER
   !! FMT ---- FORMAT TO USE
   !! START -- STARTING PLACE IN STRING
   !! STRING - PLACE TO PUT RM_Text

   USE, intrinsic :: iso_fortran_env

   USE RM_Parameters
   USE RM_Globals, only : KMSSVL, KMSSVT, KNAPVL, KNAPVT, KRMRMF, KRMDMF
   USE Maths, only : RTOD
   USE RM_Text, only : BLANK, ITOA, STRMOV, RTOA
   USE Utils, only : NDIGIT

   INCLUDE 'rmatts.inc'
   INTEGER, intent(in) :: VAL
   INTEGER, intent(in out) :: FMT
   INTEGER, intent(in) :: TYP
   INTEGER, intent(in) :: START
   INTEGER, intent(out) :: STRING(*)
   !
   INTEGER :: IV(2)
   REAL :: RVAL
   REAL(real64) :: RRVAL
   INTEGER :: WIDTH, OFFSET
   !
   !
   IF (TYP.EQ.KZINT) THEN
      !
      !    INTEGER
      !
      IF(FMT.EQ.0) FMT = NDIGIT(VAL)
      IF (VAL.EQ.ZIMISS .OR. VAL.EQ.ZINAPP) GOTO 8000
      CALL ITOA(STRING,START,FMT,VAL,IERR)
   ELSE
      !
      !    REAL
      !
      IF (VAL.EQ.ZIMISS .OR. VAL.EQ.ZINAPP) GOTO 8000
      IF (TYP.EQ.KZDOUB) THEN
         IF (FMT.EQ.0) FMT = KRMDMF
         CALL RTOA_X(STRING,START,FMT,VAL,IERR)
      ELSE
         IF (FMT.EQ.0) FMT = KRMRMF
         CALL RTOD(IV,VAL)
         RRVAL = transfer(IV,RRVAL)
         CALL RTOA(STRING,START,FMT,RRVAL,IERR)
      ENDIF
   ENDIF
   GOTO 9999
   !
   ! MISSING VALUES
   !
8000 WIDTH = MOD(FMT,100)
   CALL STRMOV(BLANK,1,WIDTH,STRING,START)
   IF(VAL.EQ.ZIMISS)THEN
      ! MISSING VALUE
      OFFSET = MAX(0,WIDTH - KMSSVL)
      CALL STRMOV(KMSSVT,1,KMSSVL,STRING,START+OFFSET)
      !CC      IF(WIDTH.EQ.0)START= START + KMSSVL
   ENDIF
   IF(VAL.EQ.ZINAPP)THEN
      ! NOT-APP VALUE
      OFFSET = MAX(0,WIDTH - KNAPVL)
      CALL STRMOV(KNAPVT,1,KNAPVL,STRING,START+OFFSET)
      !CC      IF(WIDTH.EQ.0)START= START + KNAPVL
   ENDIF

9999 CONTINUE
   RETURN
END SUBROUTINE SELPUT
